### PR TITLE
chore(RHTAPWATCH-110): Add "label_app_kubernetes_io_managed_by" label to recording rule

### PR DESCRIPTION
**Pull request by ShakedAviv50313**
* This is a second commit regarding RHTAPWATCH-110, the label "label_app_kubernetes_io_managed_by"
was added to appstudio_container_resource_limits.

* Added test cases.

### CODE REVIEW

**Review by yftacherzog — CHANGES_REQUESTED** [review]
The commit message title and PR title assume some sort of context, which might make sense now, but might make less sense if someone is to look at this change somewhere in the future.

Also, the commit message title should usually be written in an imperative form (i.e. as if you're commanding something). In this case, it means using `add label...` rather than `adding label...`.

I suggest changing the PR title and commit message title to something like this instead:

```
Add label to prometheus recording rule
```
You can mention the test cases, but I don't think this is necessary. It's expected that when we add a feature or fix a bug, we also add tests for that.

**Comment by ShakedAviv50313** [comment]
@yftacherzog  Done:)

**Review by yftacherzog — APPROVED** [review]

**Comment by yftacherzog** [comment]
> @yftacherzog Done:)

gitlint fails now. There's a limitation on the number of characters for the commit title. This cannot be addressed by breaking the title line, as the line below it needs to be empty.

It implies the need for being brief when writing the title. We should drop stuff that are unnecessary for the the title, and we can add them to the body (in this case, the name of the label can be dropped from the title).

**Review by Omeramsc — APPROVED** [review]
Besides Yftach's comments, LGTM.

**Review by avi-biton — APPROVED** [review]

**Pull request merged**
