### PR TITLE
fix: cleanup chain performance display unit, text

### PR DESCRIPTION
**Pull request by gabemontero**
Signed-off-by: Gabe Montero <gmontero@redhat.com>

rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by gabemontero** [comment]
chains-peformance-panel-fix

**Comment by gabemontero** [comment]
@amisstea PTAL

@divyansh42 FYI / education

**Review by amisstea — APPROVED** [review]

**Comment by gabemontero** [comment]
hmmm .... the lint job failed pulling its image:

```
the step "lint-yaml" in TaskRun "o11y-on-pull-request-xzkls-run-kubelint" failed to pull the image "". The pod errored with the message: "Back-off pulling image "docker.io/stackrox/kube-linter:0.2.2-2-g7d10a69154-alpine@sha256:e520e9d8d3a2dfa611914836536545b135845e7bda9f1df34b060e116232dbf0"."
```

Let's see if I have permission to retest

/retest

**Comment by gabemontero** [comment]
ok @amisstea the CI is all green now

since this is just tweaking the description / interval on one of the grafana panels, and not an alert, I'm assuming we don't have to bother the SRE folks with this one wrt the konflux email today.

Is that your understanding as well? 

thanks

**Comment by amisstea** [comment]
> since this is just tweaking the description / interval on one of the grafana panels, and not an alert, I'm assuming we don't have to bother the SRE folks with this one wrt the konflux email today.

Agreed. I'll go ahead and merge this.

**Pull request merged**
