### PR TITLE
chore(RHTAPWATCH-566): Write service monitor to scrape the metrics

### PR DESCRIPTION
**Pull request by klakshma21**
- Add service monitor to scrape the metrics

### CODE REVIEW

**Comment by yftacherzog** [comment]
Does it actually work? Are you able to query in Openshift for the metric the exporter is generating?

**Review by hmariset — APPROVED** [review]
Able to view the service monitor metrics (request_counter) in openshift UI (Observe->metrics)

**Comment by klakshma21** [comment]
@yftacherzog @avi-biton Need your approval, the PR is now updated. It is working now and @hmariset can view the metrics. 
image

Two things that we missed were updating the commit ref number and RHTAP setup.

**Review by amisstea — APPROVED** [review]

**Pull request merged**
