### PR TITLE
fix(KFLUXBUGS-1248): invert pipeline service alerts to >0.95 percentile

### PR DESCRIPTION
**Pull request by gabemontero**
rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by gabemontero** [comment]
/hold 

while I sort out how to order changes between here and app-interface with app sre

**Comment by gabemontero** [comment]
still need to update unit tests as well IIRC

**Comment by gabemontero** [comment]
the ec failures seem unrelated to my change

**Review by yftacherzog — APPROVED** [review]

**Pull request merged**
