### PR TITLE
chore: update exporter service label

### PR DESCRIPTION
**Pull request by hmariset**
Updated the exporter service label to match
the selector in servicemonitor.

### CODE REVIEW

**Comment by yftacherzog** [comment]
@hmariset please confirm it's working in dev

**Comment by hmariset** [comment]
> @hmariset please confirm it's working in dev

image
just tested, it's working

**Review by yftacherzog — APPROVED** [review]

**Comment by yftacherzog** [comment]
@hmariset I think the on-push pipeline is still not being triggered, so you'd need to update the infra-deployments ref manually.

**Comment by hmariset** [comment]
sure, creating PR in infra-deployments

**Pull request merged**
