### PR TITLE
fix(stoneintg-761): drop snapshotEnvironmentBinding from grafana 

### PR DESCRIPTION
**Pull request by kasemAlem**
This PR as a follow up working in task [STONEINTG-761](https://issues.redhat.com/browse/STONEINTG-761)  to decouple all SnapshotEnvironmentBinding and Environments .

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
lgtm from my point of view

**Comment by dirgim** [comment]
The gitlint check is failing on the commit message header being too long

**Review by yftacherzog — CHANGES_REQUESTED** [review]
@kasemAlem I suspect some sort of rebase issue. There are 3000 files in the PR now.

**Review by yftacherzog — APPROVED** [review]

**Comment by kasemAlem** [comment]
> @kasemAlem I suspect some sort of rebase issue. There are 3000 files in the PR now.

Thanks Yiftach, 
I've fixed that rebase issue , 
now it's failing on the EC check

**Comment by kasemAlem** [comment]
@yftacherzog , I should remove the test of the removed parameter SEB  , 
[seb_created_to_ready_test.yaml](https://github.com/redhat-appstudio/o11y/blob/main/test/promql/tests/data_plane/seb_created_to_ready_test.yaml) , right ?

**Comment by yftacherzog** [comment]
> @yftacherzog , I should remove the test of the removed parameter SEB , [seb_created_to_ready_test.yaml](https://github.com/redhat-appstudio/o11y/blob/main/test/promql/tests/data_plane/seb_created_to_ready_test.yaml) , right ?

Those are tests for recording rules that still exist https://github.com/redhat-appstudio/o11y/blob/main/rhobs/alerting/data_plane/prometheus.seb_created_to_ready_alerts.yaml

I don't think those tests should be removed.

**Review by yftacherzog — CHANGES_REQUESTED** [review]
Still need to reinstate the tests

**Comment by avi-biton** [comment]
@kasemAlem As @yftacherzog mentioned, the tests should not be deleted, they are referring to the alert rules and not for the dashboards

**Comment by kasemAlem** [comment]
> @kasemAlem As @yftacherzog mentioned, the tests should not be deleted, they are referring to the alert rules and not for the dashboards

thanks for explaining @avi-biton  and @yftacherzog , I've returned the test yaml

**Comment by yftacherzog** [comment]
@kasemAlem rebase and squash the commits. I think tests should pass once you do it.

**Comment by kasemAlem** [comment]
it was corrupted with the squash , I'll create a new one

**Pull request closed without merging**
