### PR TITLE
feat(STONEINTG-559): add alert and test for SLO 6 Intg Svc

### PR DESCRIPTION
**Pull request by jencull**
add alert rule and testing for same for SLO 6
Integration Service - Snapshot Environment Binding created to ready seconds

### CODE REVIEW

**Comment by jencull** [comment]
This metric gets 1 hit every few days so 'no data' is the usual return on our own grafana panels. We had one measurement late in the day on 5th Dec. If 'no data' is returned that is to be expected. Screenshots of today (Dec 6th) panels, for reference:

image

image

**Comment by yftacherzog** [comment]
> This metric gets 1 hit every few days so 'no data' is the usual return on our own grafana panels. We had one measurement late in the day on 5th Dec. If 'no data' is returned that is to be expected. Screenshots of today (Dec 6th) panels, for reference:
> 
> image
> 
> image

Do we have a test case for that common case? i.e. confirm that things work as expected when both metrics are at zero throughout the test.

**Comment by jencull** [comment]
> > This metric gets 1 hit every few days so 'no data' is the usual return on our own grafana panels. We had one measurement late in the day on 5th Dec. If 'no data' is returned that is to be expected. Screenshots of today (Dec 6th) panels, for reference:
> > image
> > image
> 
> Do we have a test case for that common case? i.e. confirm that things work as expected when both metrics are at zero throughout the test.

There will be, later today. Thanks :)

**Comment by jencull** [comment]
That test is added now.

**Review by yftacherzog — APPROVED** [review]
lgtm

**Review by amisstea — APPROVED** [review]

**Pull request merged**
