### PR TITLE
fix(SRVKP-4521): remove AppSRE unactionable alerts

### PR DESCRIPTION
**Pull request by gabemontero**
Based on the Aug 20th Konflux arch discussion, we are starting the removal of these pipeline alerts, and they only means of resolving them without deleting all pipeline runs is to tune OpenShift Pipelines via changes to infra-deployment, which we should not expect App SRE to do

Meeting notes:  https://docs.google.com/document/d/1hT1EV-z4iKCDji6em8QRfUzZtVhGSjUswk_eh1odoc4/edit#heading=h.ufn5rv67bcz0

I'll remove the panels separately given the concurrent activity we have adding alerts for results and PAC, and the trickiness in editing Grafana panel JSON

rh-pre-commit.version: 2.3.1
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by gabemontero** [comment]
kubelint img pull flake

/retest

**Comment by gabemontero** [comment]
@amisstea @yftacherzog @redhat-appstudio/konflux-sre PTAL

@scoheb @dirgim @mmorhun FYI this stems from the arch discussion last week re: "actionable" alerts; finally getting around to removing these "need PRs to infra-deployments for resolution" alerts that I put in last year

thanks again for the discussion

**Comment by gabemontero** [comment]
also @enarha @divyansh42 @savitaashture @khrm FYI ^^

**Review by amisstea — APPROVED** [review]
Will await review from @redhat-appstudio/konflux-sre before merging.

**Comment by gabemontero** [comment]
For now put a WIP on prefix on the PR .... still debating the chains controller performance alert

**Comment by gabemontero** [comment]
> For now put a WIP on prefix on the PR .... still debating the chains controller performance alert

added the chains controller performance alert back since konflux had issues with chains perf in the past.  Also the resolution in the SOP PR is actionable for App SRE

Removing WIP prefix, ready for @redhat-appstudio/konflux-sre review

**Comment by gabemontero** [comment]
Now, after approvals, we'll have to figure out which order we merge PRs in @amisstea .... my proposal is :

- https://github.com/redhat-appstudio/o11y/pull/342
- https://github.com/redhat-appstudio/o11y/pull/354
- this PR https://github.com/redhat-appstudio/o11y/pull/350
- https://github.com/redhat-appstudio/o11y/pull/349

thanks

**Pull request merged**
