### PR TITLE
test(STONEO11Y-50): Setup pint for the CI of o11y

### PR DESCRIPTION
**Pull request by eisraeli**
[pint](https://github.com/cloudflare/pint) is a Prometheus rule linter/validator

### CODE REVIEW

**Review by Omeramsc — CHANGES_REQUESTED** [review]
As someone who doesn't know pint, a PR description will be appreciated.

**Comment by eisraeli** [comment]
> As someone who doesn't know pint, a PR description will be appreciated.

It is actually explained in the JIRA issue in one line.
It's a Prometheus rule linter/validator.

**Comment by Omeramsc** [comment]
> > As someone who doesn't know pint, a PR description will be appreciated.
> 
> It is actually explained in the JIRA issue in one line. Anyway, I've added the description on the PR description and the commit message.

That's nice, but when I `git log` I don't want to be redirected to Jira for the basic details... only to get a more informative description.

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by amisstea — APPROVED** [review]
Looks good to me. It's up to you if you want to attempt to port this to tekton.

**Pull request closed without merging**
